### ISSUE TITLE
Parameter update does not utilize the result from linesearch( ) 

### ISSUE THREAD

**Issue by zhongwen** [wojzaremba/trpo#1]
Hi Wojciech,

In https://github.com/wojzaremba/trpo/blob/master/main.py#L168-L170

```
                theta = linesearch(loss, thprev, fullstep, neggdotstepdir / lm)
                theta = thprev + fullstep
                self.sff(theta)
```

the `theta` obtained from linesearch does not affect the result, is there something wrong here? Thanks.

**Comment by wojzaremba** [comment]
Good point. Would you like to fix it, and make sure that it works after ?
